/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Doukutsu - Copie'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct _SCOPETABLE_ENTRY;

/* 1 */
#pragma pack(push, 8)
struct struct_0
{
  char anonymous_0[1144];
};
#pragma pack(pop)

/* 2 */
#pragma pack(push, 8)
struct _msEH
{
  int _unk;
  void *FilterProc;
  void *ExitProc;
};
#pragma pack(pop)

/* 22 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 23 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 3 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 4 */
#pragma pack(push, 8)
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};
#pragma pack(pop)

/* 6 */
#pragma pack(push, 8)
struct POINT
{
  LONG x;
  LONG y;
};
#pragma pack(pop)

/* 7 */
#pragma pack(push, 8)
struct RECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};
#pragma pack(pop)

/* 5 */
#pragma pack(push, 8)
struct WINDOWPLACEMENT
{
  UINT length;
  UINT flags;
  UINT showCmd;
  POINT ptMinPosition;
  POINT ptMaxPosition;
  RECT rcNormalPosition;
};
#pragma pack(pop)

/* 8 */
#pragma pack(push, 8)
struct WNDCLASSEXA
{
  UINT cbSize;
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCSTR lpszMenuName;
  LPCSTR lpszClassName;
  HICON hIconSm;
};
#pragma pack(pop)

/* 9 */
#pragma pack(push, 8)
struct tagMSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};
#pragma pack(pop)

/* 10 */
#pragma pack(push, 8)
struct MSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};
#pragma pack(pop)

/* 11 */
#pragma pack(push, 8)
struct timecaps_tag
{
  UINT wPeriodMin;
  UINT wPeriodMax;
};
#pragma pack(pop)

/* 12 */
#pragma pack(push, 8)
struct _STARTUPINFOA
{
  DWORD cb;
  LPSTR lpReserved;
  LPSTR lpDesktop;
  LPSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};
#pragma pack(pop)

/* 13 */
#pragma pack(push, 8)
struct _MEMORY_BASIC_INFORMATION
{
  PVOID BaseAddress;
  PVOID AllocationBase;
  DWORD AllocationProtect;
  SIZE_T RegionSize;
  DWORD State;
  DWORD Protect;
  DWORD Type;
};
#pragma pack(pop)

/* 14 */
#pragma pack(push, 8)
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};
#pragma pack(pop)

/* 15 */
#pragma pack(push, 8)
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
  char _padding[2];
};
#pragma pack(pop)

/* 16 */
#pragma pack(push, 8)
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};
#pragma pack(pop)

/* 18 */
#pragma pack(push, 8)
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};
#pragma pack(pop)

/* 17 */
#pragma pack(push, 8)
union LARGE_INTEGER
{
  LONGLONG anonymous_0;
  _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  __int64 QuadPart;
};
#pragma pack(pop)

/* 19 */
#pragma pack(push, 8)
struct FILE
{
  char *_ptr;
  int _cnt;
  char *_base;
  int _flag;
  int _file;
  int _charbuf;
  int _bufsiz;
  char *_tmpfname;
};
#pragma pack(pop)

/* 20 */
#pragma pack(push, 8)
struct _SYSTEM_INFO::$41710344DA04EC56A327D4EA11DEF6D2::$AA04DEB0C6383F89F13D312A174572A9
{
  WORD wProcessorArchitecture;
  WORD wReserved;
};
#pragma pack(pop)

/* 21 */
struct _SCOPETABLE_ENTRY
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 24 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 25 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 26 */
union __declspec(align(8)) __m64
{
  unsigned __int64 m64_u64;
  float m64_f32[2];
  __int8 m64_i8[8];
  __int16 m64_i16[4];
  __int32 m64_i32[2];
  __int64 m64_i64;
  unsigned __int8 m64_u8[8];
  unsigned __int16 m64_u16[4];
  unsigned __int32 m64_u32[2];
};

/* 27 */
union __declspec(align(16)) __m128
{
  float m128_f32[4];
  unsigned __int64 m128_u64[2];
  __int8 m128_i8[16];
  __int16 m128_i16[8];
  __int32 m128_i32[4];
  __int64 m128_i64[2];
  unsigned __int8 m128_u8[16];
  unsigned __int16 m128_u16[8];
  unsigned __int32 m128_u32[4];
};

/* 28 */
struct __m128d
{
  double m128d_f64[2];
};

/* 29 */
union __declspec(align(16)) __m128i
{
  __int8 m128i_i8[16];
  __int16 m128i_i16[8];
  __int32 m128i_i32[4];
  __int64 m128i_i64[2];
  unsigned __int8 m128i_u8[16];
  unsigned __int16 m128i_u16[8];
  unsigned __int32 m128i_u32[4];
  unsigned __int64 m128i_u64[2];
};

